apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail
  labels:
    app: thumbnail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thumbnail
  template:
    metadata:
      labels:
        app: thumbnail
    spec:
      containers:
        - name: thumbnail
          image: "username/thumbnail:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
